/* This file is generated by docs/scripts/sync-site-facts.mjs */
export const siteFacts = {
  "ruleCount": 132,
  "domainCount": 32,
  "localeCount": 2,
  "topDomains": [
    {
      "category": "frontend",
      "count": 26
    },
    {
      "category": "backend",
      "count": 21
    },
    {
      "category": "devops",
      "count": 12
    },
    {
      "category": "general",
      "count": 8
    },
    {
      "category": "data",
      "count": 7
    },
    {
      "category": "ai",
      "count": 6
    }
  ],
  "generatedAt": "2026-05-16T16:11:12.173Z"
} as const
